# Generated by Django 5.0.6 on 2026-07-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='workspace_type',
            field=models.CharField(choices=[('office', 'Office'), ('coworking', 'Coworking Space'), ('meeting', 'Meeting Room'), ('virtual', 'Virtual Office')], default='office', max_length=20),
        ),
    ]
