# Generated by Django 5.0.6 on 2026-08-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_office_workspace_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
