# Generated by Django 5.0.6 on 2026-08-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_officeimage_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
